[package]
name = "savesys"
version = "3.5.0"
license = "GPL-3.0"
keywords = ["gamedev", "save management", "save system"]
categories = ["game-development", "filesystem"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
